version: '3.9'

services:
  db:
    container_name: postgresdb
    image: postgres:16-alpine3.17
    restart: always
    environment:
      POSTGRES_USER: velez_reyes
      POSTGRES_PASSWORD: velez_reyes2023@#
      POSTGRES_DB: google_terms_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: djangoapp
    image: app:django
    build: ./back_end
    volumes:
      - ./back_end:/django
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_NAME=google_terms_db
      - DB_USER=velez_reyes
      - DB_PASSWORD=velez_reyes2023@#
      - DB_HOST=db
    ports:
        - '8000:8000'
    command: > 
                sh -c "python manage.py wait_for_db &&
                      python manage.py makemigrations &&  
                      python manage.py migrate && 
                      python manage.py runserver 0.0.0.0:8000"
  frontend:
    container_name: reactapp
    build: ./front_end
    volumes:
      - ./front_end:/react
    ports:
      - '9000:9000'
volumes:
  postgres-data:
    driver: local
