version: '3.9'

services:
  db:
    container_name: postgresdb
    image: postgres:16-alpine3.17
    restart: always
    environment:
      POSTGRES_USER: velez_reyes
      POSTGRES_PASSWORD: velez_reyes2023@#
      POSTGRES_DB: google_terms_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: djangoapp
    image: app:django
    build: ./back_end
    volumes:
      - ./back_end:/django
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_NAME=google_terms_db
      - DB_USER=velez_reyes
      - DB_PASSWORD=velez_reyes2023@#
      - DB_HOST=db
    ports:
        - '8000:8000'
    command: > 
                sh -c "python manage.py wait_for_db &&
                      python manage.py makemigrations &&  
                      python manage.py migrate && 
                      python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres-data:
    driver: local
CLIENT ID 116981855124741233530
POJECT ID shaped-storm-404613

Google api key 86fb7d0d29861c2a2fc727d4e2ee15753c8de7be

"-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC3FEzw498B11/9\nz/jvDmgdhaqTEgFXhS7WWsLAOpiZglsxq5gPv90RMPToRKpMDq4FsUvaTHzPCBHu\nzFmmBYWPmFF6C85FmNvV+2MHizPqUKfkMmNprJWla1rxAW1MgLwJd5HQ8nsdLrL2\n3olYaTzVo7y7sE2+iVSqqhqoKgh4feKwI2+ExFr5gLDWQYHH73NNFIpkrp89iY1j\n+55Gun3nesoJDOVSgfbJx9l8YivYIuIRgY6uRPCVk29e/TmKZEbNZ1As0fZbvjbo\nPq3HBFcciV4vcSuddoJ20gNr55oxvWfd1OzW3zRxjtaiIwhsjS2wskgOIA9ffhnV\nUJCJcBUnAgMBAAECggEAMKTHMLYK+c1E5wZMKRBV34o1YTBGhP+RC0lAN50aEKeP\nHWpvU7fxv/CXEeO0r9KysDaEZfMusj99rEpFg5QyAY5CD8B1RQ6xUnChxk5ZM+fM\nRBiTS2+cr0AQALsVVF9cFtPbPX4/8egHiwpjycbkcAs6SVA1x+trQJFD1eydJY4x\n7Dkb3cpmHu/8K8pQIu3+zHqPKu3x+28ORLYv5hLax4sPXG0UNpNbn3Xo05voM4CX\nGMsrKX5b1Xn1t8qZJokRNDpXp+lTgbSH7PkHfGtOqtW1KoIFe9vh7/crgNXwXb5M\nLqotF+pj8SIv+bvnDDyCCwnsgMc5CizcO51lDEoi0QKBgQDj2/a5L7frSfcRiM87\n9nBaeAqqPP+dTSbVOb2JXlpbbHZT3d7rpJtU26up2bhtX8Dgxckz6FQOrLZ0zod0\n0MTDpWPhUIIBce5EmqihLzk1+vs+ZGJsMnGVXIg0SzAWC95vyY5vnxhHvhNzuA7v\nDkoSgo/NXg8nObvT5MthNBzyOQKBgQDNsJEYBrbYMeGFm3nFivS6nfI50DFAOXAH\nXcPfXEW3zKh5hzhf63LH0aeRe2Yavx2W5OwXIsY2o0D9xd3T4WrTTi+CpTIxw1Zm\nCrV9QobiDxHWGvVX58luesJPy/DKeHwK7WJaMnoy4Q4jAeWhXwh8jlQATQKiWlVf\nO+438DvCXwKBgQCvTOdACcpBpqICR3LH+wztTTVHS66MYnLh0I5VRNXXSFawpx19\nxSIL4wTqo6oT23sUcpYc7TzeHVox+0KTSJpYusFg8wNSAUkCVsotV5t4QCNTGP/v\npc9kzc+sC7xu+aqj7jk6/vc7Gqz0dkJnAGNUYkYoBZk64Fv05SzjF6i9YQKBgB71\nXGFJYWvY1iDN7d4VtBAChdq9wyvveTUin8CWmse3PgRMneeSAIyiuZ3j/NI5wbJc\nckxpJ3xBxh5sEZ86ZmG3et8nDg7/X5msMvTPdo2/xud610KL2H2QbH6mK2/OAp2C\nbTM2Nb5CsWYDexR2wUg+A9anwKW/Aup6krhIqDXxAoGBAK4Ro+AfyEeaVXbEwgWn\nZYh1/1jjNzEBv/7vFyCOfLH8VA8CCWD+doxmvut2GSVg2QI+gusioaR6Wq4N6j7y\n8FqLFooOyBWF2hp5Vm9kzMWICsSUeQRN9OvNhXsPmbnvZ3BcTGjY9DjolftJdGmH\nUAhW4luriEc0Qzp20RZwA+ve\n-----END PRIVATE KEY-----\n",